version: '3.8'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: bible
      MYSQL_USER: euvitorr
      MYSQL_PASSWORD: euvitorr

  web:
    build: .
    command: ["/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: euvitorr
      PMA_PASSWORD: euvitorr
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
