# Generated by Django 3.2.24 on 2024-02-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Versiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('texto', models.TextField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.capitulo')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.idioma')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.livro')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.versao')),
                ('versiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.versiculo')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.livro'),
        ),
    ]
