# Generated by Django 3.2.24 on 2024-02-15 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='biblia.book')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('number', models.IntegerField()),
                ('verse', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='biblia.book')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='versao',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='versiculo',
        ),
        migrations.RemoveField(
            model_name='versiculo',
            name='capitulo',
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.DeleteModel(
            name='Referencia',
        ),
        migrations.DeleteModel(
            name='Versao',
        ),
        migrations.DeleteModel(
            name='Versiculo',
        ),
        migrations.AddField(
            model_name='verse',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='biblia.version'),
        ),
    ]
