# Generated by Django 3.2.24 on 2024-02-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0002_auto_20240215_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
