# Generated by Django 3.2.24 on 2024-02-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0005_auto_20240228_0227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
    ]
