# Generated by Django 3.2.24 on 2024-02-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('biblia', '0002_auto_20240215_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_chapter', models.IntegerField()),
                ('start_verse', models.IntegerField()),
                ('end_chapter', models.IntegerField()),
                ('end_verse', models.IntegerField()),
                ('end_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_ranges', to='biblia.book')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='anotacoes.note')),
                ('start_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_ranges', to='biblia.book')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.version')),
            ],
        ),
    ]
