# Generated by Django 3.2.24 on 2024-02-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0003_auto_20240218_0324'),
        ('anotacoes', '0002_auto_20240228_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblia.chapter'),
        ),
    ]
